# Generated by Django 3.0.8 on 2021-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sortno',
            field=models.CharField(max_length=120),
        ),
    ]
