# Generated by Django 3.0.8 on 2021-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210314_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sortno',
            field=models.PositiveIntegerField(),
        ),
    ]
