# Generated by Django 3.0.8 on 2021-03-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210314_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='user',
        ),
    ]
