# Generated by Django 3.0.8 on 2021-03-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_purchaseorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='name',
        ),
    ]
