# Generated by Django 3.0.8 on 2021-03-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_purchaseorder_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchaseorder',
        ),
    ]
