# Generated by Django 3.0.8 on 2021-03-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='partno',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
