# Generated by Django 3.0.8 on 2021-03-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_purchaseorder_partno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchaseorder',
        ),
    ]
