# Generated by Django 3.0.8 on 2021-03-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_delete_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='design',
            new_name='partno',
        ),
    ]
