# Generated by Django 3.0.8 on 2021-03-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210317_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='color',
            new_name='description',
        ),
    ]
