# Generated by Django 3.0.8 on 2021-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='style',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
