# Generated by Django 3.0.8 on 2021-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210317_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='style',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
