# Generated by Django 3.0.8 on 2021-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210317_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='standard',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
