# Generated by Django 3.0.8 on 2021-03-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
