# Generated by Django 3.0.8 on 2021-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
