# Generated by Django 3.0.8 on 2021-03-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_order_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.AddField(
            model_name='order',
            name='is_ppc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='new_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
