# Generated by Django 3.0.8 on 2021-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
    ]
