# Generated by Django 3.0.8 on 2021-04-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210411_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='partno',
            new_name='part',
        ),
    ]
