# Generated by Django 3.0.8 on 2021-04-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20210411_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amount',
        ),
    ]
