# Generated by Django 3.0.8 on 2021-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20210412_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address2',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address3',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
