# Generated by Django 3.0.8 on 2021-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20210412_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address2',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address3',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
