# Generated by Django 3.0.8 on 2021-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20210412_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address2',
            field=models.CharField(default='No Address 2', max_length=220),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address3',
            field=models.CharField(default='No Address 3', max_length=220),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postcode',
            field=models.CharField(default='No Postcode', max_length=10),
        ),
    ]
