# Generated by Django 3.0.8 on 2021-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20210412_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
