# Generated by Django 3.0.8 on 2021-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_deliveryins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryins',
            name='dimension',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryins',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
