# Generated by Django 3.0.8 on 2021-05-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20210503_0411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
