# Generated by Django 3.0.8 on 2021-05-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_deliveryorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='part',
        ),
    ]
