# Generated by Django 3.0.8 on 2021-05-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_remove_deliveryorder_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryins',
            name='part',
        ),
    ]
