# Generated by Django 3.0.8 on 2021-05-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_remove_deliveryins_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryIns',
        ),
    ]
