# Generated by Django 3.0.8 on 2021-05-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_deliveryins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
