# Generated by Django 3.0.8 on 2021-05-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_deliveryorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='part',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='deliveryins',
            name='purchaseorder',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='purchaseorder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
