# Generated by Django 3.0.8 on 2021-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='DeliveryIns',
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
