# Generated by Django 3.0.8 on 2021-05-18 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_deliveryins_deliveryorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryins',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
