# Generated by Django 3.0.8 on 2021-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20210518_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_stock',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
