# Generated by Django 3.0.8 on 2021-06-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_auto_20210604_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='order',
            name='style',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit',
        ),
    ]
