# Generated by Django 3.0.8 on 2021-06-09 07:46

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_auto_20210605_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='po_id',
            field=models.CharField(default=store.models.random_string, max_length=4),
        ),
    ]
