# Generated by Django 3.0.8 on 2021-06-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_order_po_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryIns',
        ),
    ]
