# Generated by Django 3.0.8 on 2021-07-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_deliveryins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryIns',
        ),
    ]
