# Generated by Django 3.0.8 on 2021-07-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_deliveryins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sortno',
        ),
    ]
