# Generated by Django 3.0.8 on 2021-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_remove_product_sortno'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
