# Generated by Django 3.0.8 on 2021-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_part_quan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='limit',
        ),
        migrations.AddField(
            model_name='part',
            name='limitq',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
