# Generated by Django 3.0.8 on 2021-07-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_auto_20210701_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='limitq',
            new_name='limit',
        ),
    ]
