# Generated by Django 3.0.8 on 2021-07-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
