# Generated by Django 3.0.8 on 2021-07-07 07:30

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryins',
            name='di_id',
            field=models.CharField(default=store.models.di_id, max_length=4),
        ),
    ]
