# Generated by Django 3.0.8 on 2021-07-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
