# Generated by Django 3.0.8 on 2021-07-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_deliveryins_di_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryins',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='deliveryins',
            name='variant',
        ),
    ]
