# Generated by Django 3.0.8 on 2021-07-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qu',
        ),
    ]
