# Generated by Django 3.0.8 on 2021-07-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_auto_20210707_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryins',
            name='part',
        ),
        migrations.RemoveField(
            model_name='order',
            name='part',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
