# Generated by Django 3.0.8 on 2021-07-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_auto_20210707_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partno', models.CharField(max_length=50)),
                ('partname', models.CharField(max_length=50)),
                ('stylepack', models.CharField(blank=True, max_length=50)),
                ('standardpack', models.PositiveIntegerField(default=0)),
                ('quan', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('variant', models.CharField(choices=[('STD', 'STD'), ('EXEC', 'EXEC'), ('PREM', 'PREM'), ('SE', 'SE'), ('ALL', 'ALL'), ('PREM/FLAG', 'PREM/FLAG'), ('FLAG', 'FLAG'), ('STD/EXEC', 'STD/EXEC'), ('EXEC/PREM', 'EXEC/PREM')], max_length=20)),
                ('usage', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Supplier')),
            ],
        ),
    ]
