# Generated by Django 3.0.8 on 2021-07-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_remove_order_qu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
