# Generated by Django 3.0.8 on 2021-07-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_deliveryorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryIns',
        ),
    ]
