# Generated by Django 3.0.8 on 2021-07-07 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_delete_deliveryins'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_id', models.CharField(default=store.models.di_id, max_length=4)),
                ('dimension', models.CharField(max_length=30)),
                ('box', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Part')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Supplier')),
            ],
        ),
    ]
