# Generated by Django 3.0.8 on 2021-07-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_deliveryins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_date',
            field=models.DateField(),
        ),
    ]
