# Generated by Django 3.0.8 on 2021-07-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_auto_20210712_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
