# Generated by Django 3.0.8 on 2021-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_auto_20210712_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(),
        ),
    ]
