# Generated by Django 3.0.8 on 2021-08-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_auto_20210805_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='usage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='variant',
            field=models.CharField(choices=[('STD', 'STD'), ('EXEC', 'EXEC'), ('PREM', 'PREM'), ('SE', 'SE'), ('ALL', 'ALL'), ('PREM/FLAG', 'PREM/FLAG'), ('FLAG', 'FLAG'), ('STD/EXEC', 'STD/EXEC'), ('EXEC/PREM', 'EXEC/PREM')], default='Choose', max_length=20),
        ),
    ]
