# Generated by Django 3.0.8 on 2021-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_auto_20210805_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='attn',
            field=models.CharField(default='Attn Name', max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='attn_email',
            field=models.CharField(default='Attn Email', max_length=220),
        ),
    ]
