# Generated by Django 3.0.8 on 2021-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_auto_20210806_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='stylepack',
            field=models.CharField(choices=[('Polybox', 'Polybox'), ('Rack', 'Rack'), ('Others', 'Others')], max_length=20),
        ),
    ]
