# Generated by Django 3.0.8 on 2021-09-25 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0100_auto_20210925_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryins',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
