# Generated by Django 3.0.8 on 2021-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_buyer',
            new_name='is_operation',
        ),
        migrations.AddField(
            model_name='user',
            name='is_ppc',
            field=models.BooleanField(default=False),
        ),
    ]
